name: Build

on:
  push:
    brunches: ['action-test']

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        os: [linux]
        arch: [amd64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'

    - name: Build
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        export VERSION=${{ github.ref_name }}
        make build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-built-artifact
        path: build/
